# Generated by Django 3.1.5 on 2022-12-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0004_auto_20221208_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='tracks_in_playlist', to='grunge.Track'),
        ),
    ]
