# Generated by Django 3.1.5 on 2022-12-08 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0005_auto_20221208_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('track_sequence', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grunge.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grunge.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='tracks_in_playlist', through='grunge.SequenceTrack', to='grunge.Track'),
        ),
    ]
