# Generated by Django 3.1.5 on 2022-12-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0006_auto_20221208_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencetrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_track', to='grunge.playlist'),
        ),
        migrations.AlterField(
            model_name='sequencetrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_track', to='grunge.track'),
        ),
    ]
