# Generated by Django 3.1.5 on 2022-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0007_auto_20221208_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencetrack',
            name='track_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
