# Generated by Django 3.1.5 on 2022-12-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0008_auto_20221208_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencetrack',
            name='track_sequence',
            field=models.IntegerField(unique=True),
        ),
    ]
