# Generated by Django 3.1.5 on 2022-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0009_auto_20221208_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencetrack',
            name='track_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
